### ISSUE TITLE
xUnit Testing 

### ISSUE THREAD

**Issue by IbrarShakoor** [BME-MIT-IET/iet-hf2021-undefined-team#5]
While working with the Execution of the Library Recommender there are some errors regarding the syntax and assignment operators. The details about them can find in the attachment below
![image](https://user-images.githubusercontent.com/68583803/118354284-ae474800-b56a-11eb-9e77-807b485f9602.png)

**Comment by IbrarShakoor** [comment]
Majority of the warnings which were causing different errors in the program while compiling are solved which you can find below.
![image](https://user-images.githubusercontent.com/68583803/118362379-98984980-b58f-11eb-9e6b-48957f515da5.png)


**Problem:** Size_t(data type) conversion into int which can cause data overflow or loss of the data.
**Solution:** We found all the functions which were dealing the data type conversions and convert it into size_t type which resolved these warning in the program 

![image](https://user-images.githubusercontent.com/68583803/118362589-53c0e280-b590-11eb-886f-901af090e45d.png)

**Comment by IbrarShakoor** [comment]
Setting the environment for xUnit testing by installing the GoogleTest Sofware
![image](https://user-images.githubusercontent.com/68583803/118369990-ec159200-b5a5-11eb-848a-fe3b551d8fa6.png)

**Comment by idreesshaikh** [comment]
I decided to write the makefile to run the pre-written tests either by making makefile file which has some errors or test and test_suite is not suitable. We have all the necessary Uni Testing files present inside our repository but don't have a callable makefile to automate this process.
