### ISSUE TITLE
Design and Document Manual Test

### ISSUE THREAD

**Issue by IbrarShakoor** [BME-MIT-IET/iet-hf2021-undefined-team#8]
The second technique that we decided to work with after Unit Testing was Manual Testing. 
The purpose of manual testing is to check if all the modules of a given library are working properly with human-designed inputs.

HERE WE'RE DESIGNING THE MANUAL TESTS:
![image](https://user-images.githubusercontent.com/68583803/118396751-415aad80-b651-11eb-93ee-503de5e2936c.png)

**Comment by IbrarShakoor** [comment]
Manual Testing 1 Providing float values:
![image](https://user-images.githubusercontent.com/68583803/118396853-b7f7ab00-b651-11eb-9e18-b9f422e1c388.png)

As you can see above we provide float values as raw inputs and the resulting ratings changed.

**Comment by IbrarShakoor** [comment]
Manual Testing 2 Providing string values:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/68583803/118411608-a0daac80-b695-11eb-917a-67906205d297.png)

From the above attachment, as you see we provide the string values which didn't get accept by the program and generates an error for the user that inputs like these are not acceptable.

**Comment by IbrarShakoor** [comment]
Errors find out during the testing which we resolved by solving the pointer to object notation. More description can be find from the picture below:
![Coverage fail for kfol because of pointer type issue-29](https://user-images.githubusercontent.com/68583803/118411492-2c077280-b695-11eb-9c6e-be53fc07c832.png)

**Comment by IbrarShakoor** [comment]
@idreesshaikh Can you confirm all these Changes.......!!!

**Comment by idreesshaikh** [comment]
@IbrarShakoor I think we need a bit more robust tests, but so far it looks ok! I will close this thread!
