### ISSUE TITLE
Programe Test Coverage 

### ISSUE THREAD

**Issue by IbrarShakoor** [BME-MIT-IET/iet-hf2021-undefined-team#9]
The main purpose of this test coverage is to run the program with the help of software called "OpencppCoverage" to analyze the code coverage that which line of the code gets execute and which not while executing.

**Shuffle Folder Test Coverage:**
![image](https://user-images.githubusercontent.com/68583803/118409259-ce215d80-b689-11eb-825b-3fd7e80c059c.png)

As in the Description below, it's also showing the warning messages along with some errors. The reason behind all these messages and errors are the usage of unsafe string function in the program such as **strcpy(), strlen() etc** . We can easily resolve these minor messages with the help of iteration of the loop or some other easy built-in functions.

**Comment by IbrarShakoor** [comment]
This is already testing done by the library programmer. With the help of OpenCPPCoverage, we were able to determine which files contain the maximum number of lines execution while program compiling. Information related to all these things can find below:
**Tests Folder Test Coverage:**
![image](https://user-images.githubusercontent.com/68583803/118409365-5f90cf80-b68a-11eb-8d47-8758cf10d000.png)


**Note:** ALL THE HEADER AND CPP FILES IN this FOLDER TOOK PART WHILE TESTING THE INPUTS WHICH CAN give US THE IDEA OF HOW MUCH THIS LIBRARY PROGRAM IS RELIABLE AND ERROR-FREE.

**Comment by IbrarShakoor** [comment]
**Test Coverage for folder kfold:**
While working with the kfold test coverage we the test get failed just because of pointer-type issue. The information you can find it below:
![image](https://user-images.githubusercontent.com/68583803/118409793-7afcda00-b68c-11eb-9d97-be9010fe6c35.png)


**Note-Solution:**
In order to get the test coverage tool to work properly, we work with the code in k_fold_parameters.c file and resolved all the issues regarding this coverage blocker and got our results which can be found in the attachment below:
![image](https://user-images.githubusercontent.com/68583803/118409884-e5157f00-b68c-11eb-92ea-6d5bb316eb1c.png)

**Comment by IbrarShakoor** [comment]
**Test Coverage for hiredis folder:**
Finally, we were able to finish the test coverage of the last folder of the given library which you can find below:
![image](https://user-images.githubusercontent.com/68583803/118410212-9d8ff280-b68e-11eb-9441-11148ded45a3.png)

**Comment by IbrarShakoor** [comment]
@idreesshaikh Please have a look at this coverage and let me know if you find something strange thank you....!!! Once you are done just close the issue..

**Comment by idreesshaikh** [comment]
@IbrarShakoor  it looks good so far! I will close it.
